name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
      name: Lint & Jest
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'

        - name: Install dependencies
          run: npm install
        
        - name: Lint
          run: npm run lint

        - name: Run Jest tests
          run: npm run test -- --coverage

        - name: Upload coverage report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report
            path: coverage/

            
  deploy: 
    name: Deploy to Netlify (prod)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy (production)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:    ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=dist --message "GitHub Actions $GITHUB_SHA"
